# Generated by Django 4.0.2 on 2022-02-26 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_slug_alter_question_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='the_answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='the_question',
        ),
    ]
