# Generated by Django 4.0.2 on 2022-02-26 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_rename_answer_answer_the_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='the_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='the_question',
            new_name='question',
        ),
    ]
