# Generated by Django 4.0.2 on 2022-03-23 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_bio_alter_userprofile_gender'),
        ('questions', '0010_alter_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='users.userprofile'),
        ),
    ]
