# Generated by Django 4.0.2 on 2022-03-23 17:58

from django.db import migrations, models
import django.db.models.deletion
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_bio_alter_userprofile_gender'),
        ('questions', '0013_alter_answer_answerer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questioner',
            field=models.ForeignKey(default=questions.models.bot, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='questions', to='users.userprofile'),
        ),
    ]
